#consants.py
ROWS = 15
COLS = 15
TILE_SIZE = 32
#Sidepanel Konstanten erstellen
SIDE_PANEL = 300
SCREEN_WIDTH = TILE_SIZE * COLS
SCREEN_HEIGHT = TILE_SIZE * ROWS
FPS = 60
#Turret Konstanten
ANIMATION_STEPS = 15
ANIMATION_DELAY = 150